# Generated by Django 5.2.3 on 2025-07-09 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_userprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='CustomUser',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='User',
            new_name='user',
        ),
    ]
