# Generated by Django 5.2.3 on 2025-07-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_customuser_bio_customuser_full_name_customuser_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('service', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('service', models.CharField(choices=[('Strategic Planning', 'Strategic Planning'), ('Business Transformation', 'Business Transformation'), ('Financial Advisory', 'Financial Advisory'), ('Human Resources', 'Human Resources'), ('Technology Consulting', 'Technology Consulting')], max_length=40)),
                ('submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
