# Generated by Django 5.2.3 on 2025-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_consultation_consultationrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.RenameField(
            model_name='consultationrequest',
            old_name='submitted',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='service',
            field=models.CharField(max_length=100),
        ),
    ]
