# Generated by Django 5.2.3 on 2025-07-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_delete_consultation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
