# Generated by Django 5.2.3 on 2025-07-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_consultationrequest_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('monthly_price', models.PositiveIntegerField(help_text='Price in dollars')),
                ('yearly_price', models.PositiveIntegerField(help_text='Price in dollars – should already include the discount')),
                ('tagline', models.CharField(help_text='Short sentence under the price', max_length=150)),
                ('badge', models.CharField(blank=True, choices=[('', ''), ('Popular', 'Popular'), ('Best Value', 'Best Value')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('features_included', models.TextField(help_text='One feature per line – prefix with ‘-’ for *excluded* items.')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
