# Generated by Django 5.2.3 on 2025-07-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_pricingplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingPlan',
        ),
    ]
